org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.java.home=D:\\Coding\\Languages\\Java\\jdk-25.0.3

maven_group=com.github.beng420
mod_id=kung
mod_name=Kung
mod_version=0.1.0
mod_description=Client-side Hypixel SkyBlock quality-of-life mod.
mod_author=Beng420
mod_license=All-Rights-Reserved
mod_version_mc26_1_2=0.2.3

loom_version=1.14.10
fabric_loader_version=0.19.2

minecraft_version_26_1_2=26.1.2
java_release_26_1_2=25
fabric_api_version_26_1_2=0.155.2+26.1.2