org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

maven_group=com.github.beng420
mod_id=kung
mod_name=Kung
mod_version=0.1.0
mod_description=Client-side Hypixel SkyBlock quality-of-life mod.
mod_author=Beng420
mod_license=All-Rights-Reserved

loom_version=1.14.10
fabric_loader_version=0.19.2

minecraft_version_1_21_11=1.21.11
java_release_1_21_11=21
fabric_api_version_1_21_11=0.141.4+1.21.11

minecraft_version_26_1_2=26.1.2
java_release_26_1_2=25
fabric_api_version_26_1_2=0.153.0+26.1.2
